image: ubuntu:22.04

variables:
  GRADLE_HOME: "/opt/gradle-8.14"
  PATH: "$GRADLE_HOME/bin:$PATH"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  NEXUS_URL: ${NEXUS_URL}
  NEXUS_USERNAME: ${NEXUS_USERNAME}
  NEXUS_PASSWORD: ${NEXUS_PASSWORD}

before_script:
  - chmod +x $GRADLE_HOME/bin/gradle
  - gradle --version

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .gradle/
    - build/

build:
  stage: build
  script:
    - gradle build -x test --no-daemon
    - echo "=== 构建的JAR包列表 ==="
    - find . -path "*/build/libs/*.jar" -type f -exec ls -lh {} \;
    - echo "=== Gradle构建产物信息 ==="
    - gradle properties | grep -E "(name|version|group)" || true
    - echo "=== 构建完成 ==="

test:
  stage: test
  script:
    - gradle test jacocoTestReport --no-daemon
  artifacts:
    paths:
      - "build/reports/"
      - "*/build/reports/"
      - "**/build/reports/"
    expire_in: 1 week

package:
  stage: package
  script:
    - gradle assemble --no-daemon
    - echo "=== 查找所有 JAR 文件 ==="
    - find . -path "*/build/libs/*.jar" -type f
    - echo "=== 打包所有 JAR 文件为 all-jars.zip ==="
    - find . -path "*/build/libs/*.jar" -type f -print0 | xargs -0 zip all-jars.zip
    - ls -lh all-jars.zip
  artifacts:
    paths:
      - all-jars.zip
    expire_in: 1 week


deploy:
  stage: deploy
  script:
    - gradle publish --no-daemon
  only:
    - main
  when: manual 